[
    "Nicholas Nickleby",
    "The Pearl",
    "Death Comes for the Archbishop",
    "The Razor's Edge",
    "Their Eyes Were Watching God",
    "P\u00e8re Goriot",
    "Native Son",
    "The Metamorphosis",
    "The Mystery of Edwin Drood",
    "Gone Girl",
    "Winesburg, Ohio",
    "Harry Potter and the Order of the Phoenix",
    "Pride and Prejudice",
    "Sula",
    "Around the World in Eighty Days",
    "The Witches",
    "The Time Traveler's Wife",
    "A Christmas Carol",
    "The Firm",
    "The Amber Spyglass",
    "Inkheart",
    "The Lucky One",
    "1984",
    "Little Women",
    "Don Quixote",
    "Sons and Lovers",
    "Watership Down",
    "The Phantom of the Opera",
    "A Time to Kill",
    "Mrs. Frisby and the Rats of NIMH",
    "A Journey To The Center Of The Earth",
    "Le Morte d'Arthur: King Arthur and the Legends of the Round Table",
    "Babbitt",
    "Tuck Everlasting",
    "The Hobbit, or There and Back Again",
    "Little House in the Big Woods",
    "The King of Torts",
    "And Then There Were None",
    "King of the Wind: The Story of the Godolphin Arabian",
    "Dreamcatcher",
    "The Betrothed",
    "Light in August",
    "Looking for Alaska",
    "The Pickwick Papers",
    "From the Mixed-Up Files of Mrs. Basil E. Frankweiler",
    "The Clan of the Cave Bear",
    "The Grapes of Wrath",
    "The Decameron",
    "Lord Jim",
    "Elijah of Buxton",
    "Snow Falling on Cedars",
    "The Grey King",
    "Absalom, Absalom!",
    "Candide",
    "Little Town on the Prairie",
    "The Pelican Brief",
    "Catch-22",
    "Our Mutual Friend",
    "Jacob Have I Loved",
    "The Idiot",
    "The Moonstone",
    "The Three Musketeers",
    "The Girl with the Dragon Tattoo",
    "Barnaby Rudge",
    "The Little Prince",
    "David Copperfield",
    "Twilight",
    "The Choice",
    "First Family",
    "Germinal",
    "Matilda",
    "Room",
    "A Prayer for Owen Meany",
    "Tess of the D'Urbervilles",
    "Catching Fire",
    "Ramona Quimby, Age 8",
    "Persuasion",
    "Memoirs of a Geisha",
    "Orlando",
    "Resurrection",
    "Heidi",
    "The Wind in the Willows",
    "Buddenbrooks: The Decline of a Family",
    "A Painted House",
    "Through the Looking-Glass and What Alice Found There",
    "The Mayor of Casterbridge",
    "The Handmaid's Tale",
    "Ender's Game",
    "Animal Farm",
    "Shirley",
    "A Passage to India",
    "Villette",
    "The Death of Ivan Ilych",
    "Misty of Chincoteague",
    "The Catcher in the Rye",
    "Arrowsmith",
    "East of Eden",
    "The Return of the Native",
    "Dear Mr. Henshaw",
    "One Flew Over the Cuckoo's Nest",
    "The Fountainhead",
    "My Side of the Mountain",
    "The Chamber",
    "Nights in Rodanthe",
    "Of Mice and Men",
    "Daughter of Fortune",
    "Tender Is the Night",
    "Ramona the Pest",
    "The Curious Incident of the Dog in the Night-Time",
    "The House of Mirth",
    "Fathers and Sons",
    "The Pilgrim's Progress",
    "The Runaway Jury",
    "The Horse Whisperer",
    "The Old Curiosity Shop",
    "Harry Potter and the Half-Blood Prince",
    "Uncle Tom's Cabin",
    "The Murder of Roger Ackroyd",
    "The Cider House Rules",
    "Madame Bovary",
    "The Mill on the Floss",
    "The Book Thief",
    "The Thorn Birds",
    "Atonement",
    "Shiloh",
    "The Forsyte Saga",
    "The Killer Angels",
    "The Golden Compass",
    "The Magician's Nephew",
    "King Solomon's Mines",
    "The Higher Power of Lucky",
    "Northanger Abbey",
    "The Camel Club",
    "Hatchet",
    "Dombey and Son",
    "The Road",
    "Lorna Doone",
    "In Cold Blood",
    "The Trial",
    "The Black Arrow",
    "Like Water for Chocolate",
    "The Tale of Despereaux",
    "Song of Solomon",
    "Prince Caspian",
    "Wuthering Heights",
    "Fahrenheit 451",
    "Dracula",
    "Inkspell",
    "Washington Square",
    "Sounder",
    "Main Street",
    "The Girl Who Kicked the Hornet's Nest",
    "The Time Machine",
    "Siddhartha",
    "The House on Mango Street",
    "Mrs. Dalloway",
    "Captains Courageous",
    "The Secret Agent",
    "A Room with a View",
    "The Five People You Meet in Heaven",
    "The Leopard",
    "Brideshead Revisited",
    "The Whipping Boy",
    "The Way of All Flesh",
    "To Have and Have Not",
    "Because of Winn-Dixie",
    "The Pillars of the Earth",
    "Beloved",
    "The Count of Monte Cristo",
    "A Portrait of the Artist as a Young Man",
    "Caddie Woodlawn",
    "The Chocolate War",
    "Jane Eyre",
    "The Ambassadors",
    "The Man in the Iron Mask",
    "O Pioneers!",
    "Oliver Twist",
    "Gone with the Wind",
    "Rebecca",
    "The Memory Keeper's Daughter",
    "Steppenwolf",
    "The Picture of Dorian Gray",
    "Peter Pan",
    "The Jungle",
    "The Return of the King",
    "This Side of Paradise",
    "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "Rebecca of Sunnybrook Farm",
    "Mansfield Park",
    "The Giver",
    "The Subtle Knife",
    "Schindler's List",
    "Cold Mountain",
    "All the King's Men",
    "Nana",
    "One Hundred Years of Solitude",
    "Carrie",
    "The Alchemist",
    "Remembrance of Things Past: Volume II - The Guermantes Way & Cities of the Plain",
    "Lord of the Flies",
    "The Indian in the Cupboard",
    "Quo Vadis",
    "The Outsiders",
    "A Thousand Splendid Suns",
    "The Broker",
    "The Hunger Games",
    "Harriet the Spy",
    "The Warden",
    "Bridge to Terabithia",
    "The Girl Who Played with Fire",
    "By the Shores of Silver Lake",
    "A Tale of Two Cities",
    "The Fault in Our Stars",
    "The Screwtape Letters",
    "Invisible Man",
    "Heart of Darkness",
    "The Lost Symbol",
    "The Martian Chronicles",
    "A Game of Thrones",
    "Harry Potter and the Chamber of Secrets",
    "Ramona and Her Father",
    "James and the Giant Peach",
    "Inferno",
    "The History of Tom Jones, a Foundling",
    "Water for Elephants",
    "Jude the Obscure",
    "The Invisible Man",
    "The Wedding",
    "The Partner",
    "Charlotte's Web",
    "The Yearling",
    "Utopia",
    "A Clockwork Orange",
    "Black Beauty",
    "The Heart of the Matter",
    "The Last Battle",
    "Number the Stars",
    "The Two Towers",
    "The Rainbow",
    "Walk Two Moons",
    "Atlas Shrugged",
    "Cry, the Beloved Country",
    "The Hound of the Baskervilles",
    "Coraline",
    "When You Reach Me",
    "It",
    "Dear John",
    "The Last Juror",
    "The Notebook",
    "The Lion, the Witch and the Wardrobe",
    "The Last of the Mohicans",
    "The Virginian: A Horseman of the Plains",
    "Roots",
    "The War of the Worlds",
    "The Moon and Sixpence",
    "The Gunslinger",
    "Harry Potter and the Deathly Hallows",
    "On the Banks of Plum Creek",
    "Adam Bede",
    "Lost Horizon",
    "The Long Winter",
    "The Tenant of Wildfell Hall",
    "The Portrait of a Lady",
    "Gulliver's Travels",
    "One Day in the Life of Ivan Denisovich",
    "Dream of the Red Chamber",
    "The Secret Garden",
    "Lady Chatterley's Lover",
    "On the Road",
    "Middlemarch",
    "Angels & Demons",
    "The Bridge of San Luis Rey",
    "Mockingjay",
    "Artemis Fowl",
    "The Prince and the Pauper",
    "The Complete Sherlock Holmes",
    "Treasure Island",
    "The Fellowship of the Ring",
    "Remembrance of Things Past: Volume I - Swann's Way & Within a Budding Grove",
    "Crime and Punishment",
    "Love in the Time of Cholera",
    "Call It Courage",
    "Stranger in a Strange Land",
    "Bleachers",
    "The Fall",
    "Of Human Bondage",
    "The English Patient",
    "The Associate",
    "The Things They Carried",
    "Bud, Not Buddy",
    "The Red Pony",
    "The Mammoth Hunters",
    "The Great Gatsby",
    "Life of Pi",
    "The Sun Also Rises",
    "Where the Red Fern Grows",
    "A Farewell to Arms",
    "My \u00c1ntonia",
    "The Spy Who Came In from the Cold",
    "Frankenstein: The 1818 Text",
    "Johnny Tremain",
    "The Adventures of Huckleberry Finn",
    "Worst Case",
    "The Da Vinci Code",
    "Breaking Dawn",
    "The BFG",
    "The Help",
    "These Happy Golden Years",
    "Mary Poppins",
    "Little House on the Prairie",
    "Deception Point",
    "Jonathan Livingston Seagull",
    "The Heart Is a Lonely Hunter",
    "Eug\u00e9nie Grandet",
    "Go Set a Watchman",
    "Little Dorrit",
    "White Fang",
    "Pinocchio",
    "The Sea of Monsters",
    "Vision in White",
    "Ivanhoe",
    "The Miraculous Journey of Edward Tulane",
    "Jurassic Park",
    "Great Expectations",
    "Fearless Fourteen",
    "Kim",
    "The Lightning Thief",
    "The Once and Future King",
    "The Silver Chair",
    "The God of Small Things",
    "Slaughterhouse-Five",
    "Cannery Row",
    "The Dark Is Rising",
    "The Kite Runner",
    "The Rainmaker",
    "My Sister's Keeper",
    "Julie of the Wolves",
    "To the Lighthouse",
    "Lolita",
    "To Kill a Mockingbird",
    "The Winter of Our Discontent",
    "Sarah, Plain and Tall",
    "Harry Potter and the Prisoner of Azkaban",
    "Howards End",
    "The Plague",
    "Hard Times",
    "Paper Towns",
    "The Summer of the Swans",
    "Flatland: A Romance of Many Dimensions",
    "The Vicar of Wakefield",
    "The Naked and the Dead",
    "Girl with a Pearl Earring",
    "The Mouse and the Motorcycle",
    "The Wizard of Oz and Other Wonderful Books of Oz: The Emerald City of Oz and Glinda of Oz",
    "Ben-Hur: A Tale of the Christ",
    "The Poisonwood Bible",
    "The Master and Margarita",
    "Doctor Zhivago",
    "Roll of Thunder, Hear My Cry",
    "Death in Venice",
    "Anna Karenina",
    "Tortilla Flat",
    "The Bridges of Madison County",
    "The Summons",
    "Pippi Longstocking",
    "Silas Marner",
    "The Shack",
    "An American Tragedy",
    "The Shining",
    "Are You There God? It's Me, Margaret",
    "Chronicle of a Death Foretold",
    "Diary of a Wimpy Kid",
    "The Stranger",
    "The Absolutely True Diary of a Part-Time Indian",
    "The Joy Luck Club",
    "The Old Man and the Sea",
    "The Name of the Rose",
    "The Sound and the Fury",
    "The Power and the Glory",
    "The House of the Spirits",
    "The Mysterious Island",
    "Cranford",
    "Nostromo",
    "The Color Purple",
    "The Red Badge of Courage",
    "All Quiet on the Western Front",
    "Sister Carrie",
    "Tales of a Fourth Grade Nothing",
    "Anne of the Island",
    "Alex Cross's Trial",
    "Cat's Cradle",
    "Ethan Frome",
    "The Adventures of Tom Sawyer",
    "For Whom the Bell Tolls",
    "Holes",
    "Women in Love",
    "The Age of Innocence",
    "Anne of Green Gables",
    "The Voyage of the Dawn Treader",
    "The Girl on the Train",
    "Nausea",
    "Darkness at Noon",
    "The No. 1 Ladies' Detective Agency",
    "The Westing Game",
    "Kidnapped",
    "Anne of Avonlea",
    "A Tree Grows in Brooklyn",
    "Look Homeward, Angel",
    "Alice's Adventures in Wonderland",
    "Finnegans Wake",
    "Harry Potter and the Goblet of Fire",
    "A Wrinkle in Time",
    "The Good Earth",
    "Eragon",
    "The Scarlet Letter",
    "Go Tell It on the Mountain",
    "Brave New World",
    "The Woman in White",
    "The Castle",
    "Les Mis\u00e9rables",
    "The Magic Mountain",
    "The Maze Runner",
    "Murder on the Orient Express",
    "A Separate Peace",
    "The Caine Mutiny",
    "The Client",
    "Cross Country",
    "Sense and Sensibility",
    "The Brethren",
    "The Quiet American",
    "A Connecticut Yankee in King Arthur's Court",
    "The Silmarillion",
    "The Bluest Eye",
    "Flowers for Algernon",
    "Miss Peregrine's Home for Peculiar Children",
    "The Cricket in Times Square",
    "The Phantom Tollbooth",
    "The Sorrows of Young Werther",
    "The Reader",
    "Old Yeller",
    "The Tale of Genji",
    "The Graveyard Book",
    "The Swiss Family Robinson",
    "Vanity Fair",
    "The Maltese Falcon",
    "The Testament",
    "Things Fall Apart",
    "The Bell Jar",
    "Ulysses",
    "Remembrance of Things Past: Volume III - The Captive, The Fugitive, & Time Regained",
    "Far From the Madding Crowd",
    "War and Peace",
    "Harry Potter and the Sorcerer's Stone",
    "The Sea Wolf",
    "Bleak House",
    "The House of the Seven Gables",
    "The Red and the Black",
    "Swann's Way",
    "The Stand",
    "As I Lay Dying",
    "The Lovely Bones",
    "Stuart Little",
    "The Street Lawyer",
    "The Wings of the Dove",
    "The Call of the Wild",
    "Robinson Crusoe",
    "The Witch of Blackbird Pond",
    "The Hitchhiker's Guide to the Galaxy",
    "Misery",
    "A Walk to Remember",
    "Sophie's Choice",
    "The Secret Life of Bees"
]