[
    "The Cabinet of Dr. Caligari",
    "The Kid",
    "Nosferatu",
    "Sherlock Jr.",
    "The Gold Rush",
    "Metropolis",
    "The General",
    "Sunrise",
    "The Circus",
    "The Passion of Joan of Arc",
    "All Quiet on the Western Front",
    "City Lights",
    "M",
    "It Happened One Night",
    "Modern Times",
    "The Grand Illusion",
    "Gone with the Wind",
    "Mr. Smith Goes to Washington",
    "The Wizard of Oz",
    "The Grapes of Wrath",
    "The Great Dictator",
    "Rebecca",
    "The Shop Around the Corner",
    "Citizen Kane",
    "The Maltese Falcon",
    "Casablanca",
    "To Be or Not to Be",
    "Double Indemnity",
    "The Best Years of Our Lives",
    "Brief Encounter",
    "It's a Wonderful Life",
    "Rome, Open City",
    "Out of the Past",
    "Bicycle Thieves",
    "The Red Shoes",
    "The Treasure of the Sierra Madre",
    "Kind Hearts and Coronets",
    "The Third Man",
    "White Heat",
    "All About Eve",
    "Rashomon",
    "Sunset Blvd.",
    "Ace in the Hole",
    "High Noon",
    "Ikiru",
    "Singin' in the Rain",
    "Umberto D.",
    "Roman Holiday",
    "The Wages of Fear",
    "Stalag 17",
    "Tokyo Story",
    "Diabolique",
    "Dial M for Murder",
    "On the Waterfront",
    "Rear Window",
    "Seven Samurai",
    "La strada",
    "Rififi",
    "The Night of the Hunter",
    "Pather Panchali",
    "12 Angry Men",
    "The Bridge on the River Kwai",
    "Throne of Blood",
    "Nights of Cabiria",
    "Paths of Glory",
    "The Seventh Seal",
    "Wild Strawberries",
    "Sweet Smell of Success",
    "Witness for the Prosecution",
    "The Hidden Fortress",
    "Touch of Evil",
    "Vertigo",
    "Anatomy of a Murder",
    "Ben-Hur",
    "North by Northwest",
    "The 400 Blows",
    "Rio Bravo",
    "Some Like It Hot",
    "The Apartment",
    "La Dolce Vita",
    "Inherit the Wind",
    "The Virgin Spring",
    "Psycho",
    "The Hustler",
    "Judgment at Nuremberg",
    "Viridiana",
    "Yojimbo",
    "Harakiri",
    "Ivan's Childhood",
    "Lawrence of Arabia",
    "The Man Who Shot Liberty Valance",
    "Sanjuro",
    "To Kill a Mockingbird",
    "What Ever Happened to Baby Jane?",
    "The Exterminating Angel",
    "8\u00bd",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "The Great Escape",
    "Winter Light",
    "High and Low",
    "The Battle of Algiers",
    "For a Few Dollars More",
    "The Sound of Music",
    "Andrei Rublev",
    "The Good, the Bad and the Ugly",
    "Persona",
    "Who's Afraid of Virginia Woolf?",
    "Cool Hand Luke",
    "The Graduate",
    "Le Samoura\u00ef",
    "2001: A Space Odyssey",
    "Planet of the Apes",
    "Rosemary's Baby",
    "Butch Cassidy and the Sundance Kid",
    "Once Upon a Time in the West",
    "Z",
    "Anand",
    "A Clockwork Orange",
    "Fiddler on the Roof",
    "The Last Picture Show",
    "The Godfather",
    "Sleuth",
    "Solaris",
    "Cries & Whispers",
    "The Exorcist",
    "Paper Moon",
    "Papillon",
    "The Sting",
    "Chinatown",
    "Dersu Uzala",
    "The Godfather Part II",
    "Monty Python and the Holy Grail",
    "A Woman Under the Influence",
    "Young Frankenstein",
    "Mirror",
    "Barry Lyndon",
    "Dog Day Afternoon",
    "Jaws",
    "One Flew Over the Cuckoo's Nest",
    "Sholay",
    "The Message",
    "Network",
    "Rocky",
    "Taxi Driver",
    "Annie Hall",
    "Star Wars: Episode IV - A New Hope",
    "The Deer Hunter",
    "Autumn Sonata",
    "Alien",
    "Apocalypse Now",
    "Life of Brian",
    "Stalker",
    "The Blues Brothers",
    "The Elephant Man",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Raging Bull",
    "The Shining",
    "Das Boot",
    "Raiders of the Lost Ark",
    "Blade Runner",
    "E.T. the Extra-Terrestrial",
    "Fanny and Alexander",
    "Fitzcarraldo",
    "Gandhi",
    "Pink Floyd: The Wall",
    "The Thing",
    "Star Wars: Episode VI - Return of the Jedi",
    "Scarface",
    "Amadeus",
    "Nausica\u00e4 of the Valley of the Wind",
    "Once Upon a Time in America",
    "Paris, Texas",
    "The Terminator",
    "Back to the Future",
    "Ran",
    "Aliens",
    "Come and See",
    "Jean de Florette",
    "Platoon",
    "Stand by Me",
    "Castle in the Sky",
    "Goodbye, Children",
    "Full Metal Jacket",
    "The Princess Bride",
    "Akira",
    "Die Hard",
    "Grave of the Fireflies",
    "Cinema Paradiso",
    "Rain Man",
    "My Neighbor Totoro",
    "Dead Poets Society",
    "Do the Right Thing",
    "Time of the Gypsies",
    "Indiana Jones and the Last Crusade",
    "Dances with Wolves",
    "Edward Scissorhands",
    "Goodfellas",
    "Beauty and the Beast",
    "Raise the Red Lantern",
    "JFK",
    "The Silence of the Lambs",
    "Terminator 2: Judgment Day",
    "Aladdin",
    "Reservoir Dogs",
    "Scent of a Woman",
    "Unforgiven",
    "Farewell My Concubine",
    "Groundhog Day",
    "In the Name of the Father",
    "Jurassic Park",
    "The Nightmare Before Christmas",
    "Schindler's List",
    "True Romance",
    "Andaz Apna Apna",
    "Chungking Express",
    "Forrest Gump",
    "The Lion King",
    "L\u00e9on: The Professional",
    "Pulp Fiction",
    "The Shawshank Redemption",
    "Three Colors: Red",
    "Before Sunrise",
    "Braveheart",
    "Casino",
    "Dilwale Dulhania Le Jayenge",
    "La haine",
    "Heat",
    "Se7en",
    "Toy Story",
    "12 Monkeys",
    "Underground",
    "The Usual Suspects",
    "The Bandit",
    "Fargo",
    "Secrets & Lies",
    "Sling Blade",
    "Trainspotting",
    "In the Mood for Love",
    "The Big Lebowski",
    "Boogie Nights",
    "Life Is Beautiful",
    "Black Cat, White Cat",
    "Children of Heaven",
    "Good Will Hunting",
    "L.A. Confidential",
    "Princess Mononoke",
    "Titanic",
    "The Truman Show",
    "American History X",
    "The Green Mile",
    "The Legend of 1900",
    "Lock, Stock and Two Smoking Barrels",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Saving Private Ryan",
    "Shrek",
    "The Iron Giant",
    "The Matrix",
    "Fight Club",
    "Central Station",
    "The Celebration",
    "Perfect Blue",
    "The Straight Story",
    "Mulholland Drive",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "The Sixth Sense",
    "Lagaan: Once Upon a Time in India",
    "American Beauty",
    "Neon Genesis Evangelion: The End of Evangelion",
    "Gladiator",
    "Magnolia",
    "Requiem for a Dream",
    "Almost Famous",
    "Monsters, Inc.",
    "Sarfarosh",
    "Children of Men",
    "Snatch",
    "Memento",
    "Am\u00e9lie",
    "Hera Pheri",
    "Yi Yi",
    "Spirited Away",
    "Amores Perros",
    "Donnie Darko",
    "The Pianist",
    "Everything's Gonna Be Great",
    "Catch Me If You Can",
    "Finding Nemo",
    "Kill Bill: Vol. 1",
    "A Beautiful Mind",
    "Vizontele",
    "Dogville",
    "Dil Chahta Hai",
    "My Sassy Girl",
    "Harry Potter and the Prisoner of Azkaban",
    "City of God",
    "The Incredibles",
    "Big Fish",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Eternal Sunshine of the Spotless Mind",
    "Infernal Affairs",
    "Howl's Moving Castle",
    "Cinderella Man",
    "Memories of Murder",
    "The Secret Life of Walter Mitty",
    "Inglourious Basterds",
    "Downfall",
    "Oldboy",
    "Shaun of the Dead",
    "Swades",
    "Jurassic World",
    "The Sea Inside",
    "Iron Man",
    "Batman Begins",
    "Spring, Summer, Fall, Winter... and Spring",
    "Munna Bhai M.B.B.S.",
    "Black",
    "Kill Bill: Vol. 2",
    "Casino Royale",
    "Before Sunset",
    "Ratatouille",
    "G.O.R.A.",
    "Tae Guk Gi: The Brotherhood of War",
    "Hotel Rwanda",
    "Tangled",
    "The Diving Bell and the Butterfly",
    "John Carter",
    "Sin City",
    "The Lives of Others",
    "Million Dollar Baby",
    "Rang De Basanti",
    "The Departed",
    "Nobody Knows",
    "Cowboys & Aliens",
    "The A-Team",
    "Fantastic Mr. Fox",
    "Real Steel",
    "V for Vendetta",
    "Toy Story 3",
    "Alita: Battle Angel",
    "The Bourne Ultimatum",
    "Lincoln",
    "Scott Pilgrim vs. the World",
    "Shazam!",
    "Blood Diamond",
    "Wonder Woman",
    "Life of Pi",
    "The Pursuit of Happyness",
    "The Equalizer",
    "Carry On, Munna Bhai",
    "Pan's Labyrinth",
    "Captain America: The First Avenger",
    "The Dark Knight",
    "There Will Be Blood",
    "Ex Machina",
    "Prince of Persia: The Sands of Time",
    "My Father and My Son",
    "Unstoppable",
    "No Country for Old Men",
    "Ant-Man",
    "The Croods",
    "The Prestige",
    "Avatar",
    "Love & Other Drugs",
    "Into the Wild",
    "Man of Steel",
    "Drive",
    "In Bruges",
    "Dallas Buyers Club",
    "Jack Reacher",
    "Star Trek",
    "Clash of the Titans",
    "Thor",
    "Warcraft",
    "Persepolis",
    "Interstellar",
    "World War Z",
    "Dracula Untold",
    "Godzilla",
    "Hotel Transylvania",
    "The Town",
    "The Avengers",
    "Elite Squad",
    "Jungle Cruise",
    "Chak De! India",
    "How to Train Your Dragon",
    "Shrek Forever After",
    "The Hobbit: An Unexpected Journey",
    "WALL\u00b7E",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Salt",
    "Source Code",
    "Black Swan",
    "The Amazing Spider-Man",
    "Robin Hood",
    "The Fighter",
    "Hugo",
    "Justice League",
    "Mary and Max",
    "Sucker Punch",
    "The Adventures of Tintin",
    "Machete",
    "Like Stars on Earth",
    "Hanna",
    "The Wolf of Wall Street",
    "Megamind",
    "Slumdog Millionaire",
    "Knight and Day",
    "Alice in Wonderland",
    "All Quiet on the Western Front",
    "Soorarai Pottru",
    "Argo",
    "The Father",
    "Sardar Udham",
    "Hachi: A Dog's Tale",
    "Shershaah",
    "Article 15",
    "The Descendants",
    "John Wick: Chapter 4",
    "CODA",
    "The Book of Eli",
    "Miracle in Cell No. 7",
    "Silver Linings Playbook",
    "Up",
    "The Invisible Man",
    "Thor: Love and Thunder",
    "Boyhood",
    "Departures",
    "K.G.F: Chapter 2",
    "Skyfall",
    "Dark Shadows",
    "The Kashmir Files",
    "The Matrix Resurrections",
    "Spider-Man: No Way Home",
    "Lone Survivor",
    "Paul",
    "Ant-Man and the Wasp: Quantumania",
    "Nope",
    "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train",
    "TRON: Legacy",
    "Wrath of Man",
    "The Northman",
    "Blue Valentine",
    "The Ides of March",
    "Don't Look Up",
    "Shutter Island",
    "Green Lantern",
    "The Karate Kid",
    "Glass Onion",
    "Dune",
    "The Hobbit: The Desolation of Smaug",
    "The Breath",
    "10 Cloverfield Lane",
    "The Banshees of Inisherin",
    "Prey",
    "3 Idiots",
    "The Lincoln Lawyer",
    "Rango",
    "The Bourne Legacy",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Gran Torino",
    "Moneyball",
    "The Lone Ranger",
    "Doctor Strange",
    "Escape Plan",
    "Lawless",
    "First Man",
    "The World's End",
    "Cars 2",
    "Brave",
    "Limitless",
    "Ghost in the Shell",
    "Ip Man",
    "Iron Man 2",
    "Mission: Impossible - Ghost Protocol",
    "Due Date",
    "21 Jump Street",
    "RoboCop",
    "Drishyam 2",
    "Zack Snyder's Justice League",
    "The Tourist",
    "This Is the End",
    "RED",
    "Kick-Ass",
    "300: Rise of an Empire",
    "Incendies",
    "Bullet Train",
    "The Cabin in the Woods",
    "Venom",
    "X-Men: First Class",
    "2 Guns",
    "Looper",
    "A Wednesday",
    "Easy A",
    "Bad Teacher",
    "The Social Network",
    "Ghostbusters",
    "Teenage Mutant Ninja Turtles",
    "Warrior",
    "Pirates of the Caribbean: On Stranger Tides",
    "Iron Man 3",
    "The Irishman",
    "Kung Fu Panda 2",
    "The Secret in Their Eyes",
    "50/50",
    "Rise of the Planet of the Apes",
    "The Expendables",
    "Gangster Squad",
    "Despicable Me",
    "Past Lives",
    "The Twilight Saga: Breaking Dawn - Part 1",
    "The Twilight Saga: Eclipse",
    "Terminator Genisys",
    "Tinker Tailor Soldier Spy",
    "The Great Gatsby",
    "Dredd",
    "The Dark Knight Rises",
    "Passengers",
    "Tomb Raider",
    "Cloud Atlas",
    "Inception",
    "Grown Ups",
    "The Adjustment Bureau",
    "The Other Guys",
    "Suicide Squad",
    "Total Recall",
    "The Hunger Games",
    "Mad Max: Fury Road",
    "Prisoners",
    "It",
    "Taken 2",
    "Straight Outta Compton",
    "Transformers: Dark of the Moon",
    "Unknown",
    "True Grit",
    "Star Trek Into Darkness",
    "Men in Black 3",
    "No Strings Attached",
    "The Hangover Part II",
    "Predators",
    "Hansel & Gretel: Witch Hunters",
    "The Wolverine",
    "Deadpool",
    "Rio",
    "Battleship",
    "Prometheus",
    "Monsters University",
    "The Help",
    "Gravity",
    "The Conjuring",
    "The Next Three Days",
    "Uncharted",
    "I Am Number Four",
    "Baywatch",
    "Aquaman",
    "Bridesmaids",
    "Oblivion",
    "The Greatest Showman",
    "Central Intelligence",
    "The Lego Movie",
    "Horrible Bosses",
    "The King's Speech",
    "Jai Bhim",
    "Sherlock Holmes: A Game of Shadows",
    "Barbie",
    "A Star Is Born",
    "Kantara",
    "Elysium",
    "Captain Phillips",
    "Oppenheimer",
    "127 Hours",
    "Drishyam 2",
    "Elite Squad 2: The Enemy Within",
    "Zindagi Na Milegi Dobara",
    "Just Go with It",
    "The Girl with the Dragon Tattoo",
    "Crazy, Stupid, Love.",
    "Maleficent",
    "Warm Bodies",
    "Insidious",
    "Fast Five",
    "The Big Short",
    "Contagion",
    "Safe House",
    "The Grey",
    "American Reunion",
    "Midnight in Paris",
    "A Good Day to Die Hard",
    "The Vow",
    "Paan Singh Tomar",
    "Oz the Great and Powerful",
    "Avatar: The Way of Water",
    "Edge of Tomorrow",
    "Friends with Benefits",
    "Project X",
    "In Time",
    "Ted",
    "The Man from U.N.C.L.E.",
    "Udaan",
    "The Dictator",
    "How to Train Your Dragon 2",
    "The Gray Man",
    "The Impossible",
    "Super 8",
    "Kick-Ass 2",
    "The Artist",
    "The Perks of Being a Wallflower",
    "The Revenant",
    "Pacific Rim",
    "Ice Age: Continental Drift",
    "Now You See Me",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "The Intouchables",
    "Ready Player One",
    "Despicable Me 2",
    "Sausage Party",
    "Chronicle",
    "Snowpiercer",
    "Les Mis\u00e9rables",
    "We're the Millers",
    "Shame",
    "Bohemian Rhapsody",
    "Ender's Game",
    "Snow White and the Huntsman",
    "Top Gun: Maverick",
    "Moonrise Kingdom",
    "The Expendables 2",
    "Wreck-It Ralph",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "The Maze Runner",
    "Zero Dark Thirty",
    "Southpaw",
    "Her",
    "American Hustle",
    "After Earth",
    "The Place Beyond the Pines",
    "Kahaani",
    "Chappie",
    "Black Panther",
    "A Separation",
    "Divergent",
    "Captain America: The Winter Soldier",
    "Django Unchained",
    "End of Watch",
    "Blade Runner 2049",
    "Song of the Sea",
    "The Amazing Spider-Man 2",
    "The Judge",
    "The Batman",
    "X-Men: Days of Future Past",
    "Spotlight",
    "The Raid: Redemption",
    "Fast & Furious 6",
    "Flight",
    "Sinister",
    "Seven Psychopaths",
    "Ford v Ferrari",
    "The Hangover Part III",
    "The Hunger Games: Catching Fire",
    "The Hunger Games: Mockingjay - Part 1",
    "The Hunger Games: Mockingjay - Part 2",
    "Gangs of Wasseypur",
    "Noah",
    "The Hitman's Bodyguard",
    "King Arthur: Legend of the Sword",
    "Rush",
    "Toy Story 4",
    "Pain & Gain",
    "Thor: The Dark World",
    "Pitch Perfect",
    "Neighbors",
    "War Dogs",
    "Guardians of the Galaxy",
    "Non-Stop",
    "12 Years a Slave",
    "Barfi!",
    "The Imitation Game",
    "Sita Ramam",
    "Assassin's Creed",
    "Inside Out",
    "Dawn of the Planet of the Apes",
    "The Hunt",
    "Transformers: Age of Extinction",
    "Hacksaw Ridge",
    "San Andreas",
    "Wolf Children",
    "The Accountant",
    "American Sniper",
    "The Purge",
    "About Time",
    "Transcendence",
    "Don Jon",
    "The Internship",
    "Big Hero 6",
    "Spider-Man: Homecoming",
    "Gone Girl",
    "Finding Dory",
    "The Grand Budapest Hotel",
    "Jumanji: Welcome to the Jungle",
    "OMG: Oh My God!",
    "Minions",
    "22 Jump Street",
    "Frozen",
    "Olympus Has Fallen",
    "The Hobbit: The Battle of the Five Armies",
    "Alien: Covenant",
    "Enemy",
    "The Babadook",
    "Fifty Shades of Grey",
    "Blue Jasmine",
    "White House Down",
    "PK",
    "The Mummy",
    "Bhaag Milkha Bhaag",
    "The Intern",
    "Special 26",
    "Spectre",
    "Coco",
    "Mission: Impossible - Rogue Nation",
    "Focus",
    "No Time to Die",
    "Avengers: Age of Ultron",
    "Predestination",
    "The Magnificent Seven",
    "Atomic Blonde",
    "Taken 3",
    "The Adam Project",
    "Star Wars: Episode VII - The Force Awakens",
    "Star Wars: Episode VIII - The Last Jedi",
    "Star Wars: Episode IX - The Rise of Skywalker",
    "Arrival",
    "Wonder",
    "Birdman or (The Unexpected Virtue of Ignorance)",
    "The Tale of The Princess Kaguya",
    "Hell or High Water",
    "Whiplash",
    "The Fault in Our Stars",
    "Jojo Rabbit",
    "Baahubali: The Beginning",
    "Ted 2",
    "Star Trek Beyond",
    "Me Before You",
    "Game Night",
    "The Secret Life of Pets",
    "Fury",
    "Everest",
    "Bird Box",
    "Winter Sleep",
    "Beauty and the Beast",
    "The Interview",
    "Annihilation",
    "Kingsman: The Secret Service",
    "Furious 7",
    "Nightcrawler",
    "Lucy",
    "Chef",
    "The Divergent Series: Insurgent",
    "John Wick",
    "Ad Astra",
    "Zootopia",
    "Soul",
    "Encanto",
    "Batman v Superman: Dawn of Justice",
    "The Theory of Everything",
    "Tangerines",
    "Wild Tales",
    "The Jungle Book",
    "The Conjuring 2",
    "Creed",
    "Spy",
    "Now You See Me 2",
    "Room",
    "Fantastic Beasts and Where to Find Them",
    "Cruella",
    "It Follows",
    "Sully",
    "Little Women",
    "Logan",
    "Queen",
    "X-Men: Apocalypse",
    "Haider",
    "Sicario",
    "Murder on the Orient Express",
    "Drishyam",
    "War for the Planet of the Apes",
    "The Hateful Eight",
    "The Lobster",
    "Black Widow",
    "Captain America: Civil War",
    "Thor: Ragnarok",
    "Moana",
    "American Made",
    "Captain Fantastic",
    "Incredibles 2",
    "Mommy",
    "The Martian",
    "Bridge of Spies",
    "Elvis",
    "Kong: Skull Island",
    "Lion",
    "Rogue One: A Star Wars Story",
    "Solo: A Star Wars Story",
    "La La Land",
    "The Nice Guys",
    "Bajrangi Bhaijaan",
    "Baby Driver",
    "Guardians of the Galaxy Vol. 2",
    "The Handmaiden",
    "Manchester by the Sea",
    "Maze Runner: The Scorch Trials",
    "Fantastic Beasts: The Crimes of Grindelwald",
    "Captain Marvel",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Don't Breathe",
    "M.S. Dhoni: The Untold Story",
    "Jason Bourne",
    "The Witch",
    "John Wick: Chapter 2",
    "Drishyam",
    "Ghostbusters: Afterlife",
    "Nocturnal Animals",
    "Darkest Hour",
    "The Fate of the Furious",
    "Spider-Man: Into the Spider-Verse",
    "Masaan",
    "Kingsman: The Golden Circle",
    "Klaus",
    "The Meg",
    "Hidden Figures",
    "Baahubali 2: The Conclusion",
    "The Invisible Guest",
    "Jurassic World: Fallen Kingdom",
    "Mission: Impossible - Fallout",
    "Lady Bird",
    "Talvar",
    "Split",
    "Moonlight",
    "Dunkirk",
    "Three Billboards Outside Ebbing, Missouri",
    "Godzilla vs. Kong",
    "Get Out",
    "Dangal",
    "The Favourite",
    "Ant-Man and the Wasp",
    "Mother!",
    "Ocean's Eight",
    "Wolfwalkers",
    "Your Name.",
    "A Silent Voice: The Movie",
    "Wind River",
    "Life",
    "Deadpool 2",
    "Bright",
    "Killers of the Flower Moon",
    "Pink",
    "I, Tonya",
    "The Shape of Water",
    "Doctor Sleep",
    "Train to Busan",
    "Call Me by Your Name",
    "Uncut Gems",
    "The Lion King",
    "Aladdin",
    "John Wick: Chapter 3 - Parabellum",
    "Vikram Vedha",
    "Free Guy",
    "Ayla: The Daughter of War",
    "Spider-Man: Far from Home",
    "The Suicide Squad",
    "Black Adam",
    "Upgrade",
    "Dark Phoenix",
    "The Wild Pear Tree",
    "A Quiet Place",
    "Everything Everywhere All at Once",
    "The Super Mario Bros. Movie",
    "Tenet",
    "Parasite",
    "Guardians of the Galaxy Vol. 3",
    "Fast & Furious Presents: Hobbs & Shaw",
    "Glass",
    "Us",
    "Green Book",
    "96",
    "Raatchasan",
    "Venom: Let There Be Carnage",
    "Wonder Woman 1984",
    "Once Upon a Time in Hollywood",
    "Joker",
    "BlacKkKlansman",
    "It Chapter Two",
    "Rangasthalam 1985",
    "777 Charlie",
    "Marriage Story",
    "Birds of Prey",
    "Hereditary",
    "K.G.F: Chapter 1",
    "Enola Holmes",
    "Nobody",
    "Jumanji: The Next Level",
    "The Lighthouse",
    "Red Notice",
    "Andhadhun",
    "The Platform",
    "Tumbbad",
    "Capernaum",
    "Uri: The Surgical Strike",
    "A Quiet Place Part II",
    "The Gentlemen",
    "Hamilton",
    "1917",
    "Portrait of a Lady on Fire",
    "Quo Vadis, Aida?",
    "Midsommar",
    "Extraction",
    "Knives Out",
    "Eternals",
    "Chhichhore",
    "Black Panther: Wakanda Forever",
    "Vikram",
    "El Camino: A Breaking Bad Movie",
    "Rocketry: The Nambi Effect",
    "Spider-Man: Across the Spider-Verse",
    "Shang-Chi and the Legend of the Ten Rings",
    "Doctor Strange in the Multiverse of Madness",
    "Asuran",
    "Promising Young Woman",
    "The Menu",
    "The Tomorrow War",
    "Kaithi"
]